name: Push to production

on:
  workflow_dispatch

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USERNAME}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Docker pull
        run: docker pull ghcr.io/frederikskaj2/homepage:test
      - name: Docker tag
        run: docker tag ghcr.io/frederikskaj2/homepage:test ghcr.io/frederikskaj2/homepage:production
      - name: Docker push
        run: docker push ghcr.io/frederikskaj2/homepage:production
      - name: Deploy container
        run: "curl --request POST '${{secrets.AZURE_WEBHOOK_PRODUCTION}}' -H 'Content-Type: application/json' -d '{}'"
      - name: Get source
        uses: actions/checkout@v2
      - name: Get timestamp
        run: echo "TIMESTAMP=`TZ=Europe/Copenhagen date +"%d-%m-%Y %H:%M"`" >> $GITHUB_ENV
      - name: Get short commit SHA
        run: echo "COMMITSHORT=`echo ${{github.sha}} | cut -c-10`" >> $GITHUB_ENV
      - name: Post to Teams
        run: >
          sed -e 's/TIMESTAMP/${{env.TIMESTAMP}}/' -e s/COMMITSHORT/${{env.COMMITSHORT}}/ -e s/COMMITLONG/${{github.sha}}/ .github/workflows/push-to-production-success.json | curl -d @- -H 'Content-Type: application/json' -X POST ${{secrets.TEAMS_WEBHOOK}}